file updated

diff --git a/.github/workflows/release-go-libs.yaml b/.github/workflows/release-go-libs.yaml
--- a/.github/workflows/release-go-libs.yaml
+++ b/.github/workflows/release-go-libs.yaml
@@ -44,47 +44,56 @@ jobs:
               "ref": "${{ github.ref }}", 
               "sha": "${{ github.sha }}"
             }
-
-  wait_for_completion:
-    name: Wait for Release Completion
-    runs-on: ubuntu-latest
-    needs: release_independent_repos
-    strategy:
-      matrix:
-        repo: ["khareRajshree/goiscsi", "khareRajshree/gonvme"]
-    steps:
-      - name: Check status of triggered workflows for release of independent repos
+      - name: Check status of triggered workflows for release of dependent repos ${{ matrix.repo }}
+        if: ${{ contains('["khareRajshree/goiscsi", "khareRajshree/gonvme"]', matrix.repo) }}
         run: |
           # GitHub access token
           GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
           POLL_INTERVAL=60  # Check every 60 seconds
           RETRY_COUNT=0
           MAX_RETRIES=5
-
+          POLL_INTERVAL=10
           REPO="${{ matrix.repo }}"
           echo "Checking workflow status for ${REPO}..."
 
           while true; do
-            # Get the latest workflow run status for the specified event type
-            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-              "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
+          # Get the latest workflow run status for the specified event type
+          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
 
-            # Check if the API call was successful
-            if [ $? -ne 0 ]; then
-              RETRY_COUNT=$((RETRY_COUNT + 1))
-              if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
-                echo "API call failed after $MAX_RETRIES attempts."
-                exit 1
-              else
-                echo "API call failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
-                sleep 5
-                continue
-              fi
+          # Check if the API call was successful
+          if [ $? -ne 0 ]; then
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+              echo "API call failed after $MAX_RETRIES attempts."
+              exit 1
+            else
+              echo "API call failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
+              sleep 5
+              continue
             fi
+          fi
 
-            # Parse the JSON response to get the workflow run status
-            STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
-            CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+          # Parse the JSON response to get the workflow run status
+          STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
+          CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+
+          # Reset retry count if API call was successful
+          RETRY_COUNT=0
+
+          # Continuously polls for the in_progress status of the most recently submitted workflow.
+          # Once it finds an in_progress workflow, it will keep polling until the workflow
+          # is completed successfully or failed.
+          if [ "${STATUS}" == "in_progress" ]; then
+            WORKFLOW_ID=$(echo "$RESPONSE" | jq -r '.workflow_runs[0].id')
+            echo "Workflow ID is: $WORKFLOW_ID"
+            echo "Workflow in progress for ${REPO}."
+
+            while [ "${STATUS}" == "in_progress" ]; do
+              sleep "$POLL_INTERVAL"
+              RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
+              STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
+              CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+            done
 
             if [ "${STATUS}" == "completed" ]; then
               if [ "${CONCLUSION}" == "success" ]; then
@@ -94,11 +103,13 @@ jobs:
                 echo "Workflow failed for ${REPO}."
                 exit 1
               fi
-            else
-              echo "Workflow not completed yet for ${REPO}. Waiting for $POLL_INTERVAL seconds..."
-              sleep "$POLL_INTERVAL"
             fi
-          done
+          else
+            echo "No in-progress workflow found for ${REPO}. Waiting for $POLL_INTERVAL seconds..."
+          fi
+
+          sleep "$POLL_INTERVAL"
+        done
 
   release_dependent_repo:
     name: Release Dependent Go Libraries
@@ -126,31 +137,48 @@ jobs:
           POLL_INTERVAL=60  # Check every 60 seconds
           RETRY_COUNT=0
           MAX_RETRIES=5
-
+          POLL_INTERVAL=10
           REPO="${{ matrix.repo }}"
           echo "Checking workflow status for ${REPO}..."
 
           while true; do
-            # Get the latest workflow run status for the specified event type
-            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-              "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
+          # Get the latest workflow run status for the specified event type
+          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
 
-            # Check if the API call was successful
-            if [ $? -ne 0 ]; then
-              RETRY_COUNT=$((RETRY_COUNT + 1))
-              if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
-                echo "API call failed after $MAX_RETRIES attempts."
-                exit 1
-              else
-                echo "API call failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
-                sleep 5
-                continue
-              fi
+          # Check if the API call was successful
+          if [ $? -ne 0 ]; then
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+              echo "API call failed after $MAX_RETRIES attempts."
+              exit 1
+            else
+              echo "API call failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
+              sleep 5
+              continue
             fi
+          fi
 
-            # Parse the JSON response to get the workflow run status
-            STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
-            CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+          # Parse the JSON response to get the workflow run status
+          STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
+          CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+
+          # Reset retry count if API call was successful
+          RETRY_COUNT=0
+
+          # Continuously polls for the in_progress status of the most recently submitted workflow.
+          # Once it finds an in_progress workflow, it will keep polling until the workflow
+          # is completed successfully or failed.
+          if [ "${STATUS}" == "in_progress" ]; then
+            WORKFLOW_ID=$(echo "$RESPONSE" | jq -r '.workflow_runs[0].id')
+            echo "Workflow ID is: $WORKFLOW_ID"
+            echo "Workflow in progress for ${REPO}."
+
+            while [ "${STATUS}" == "in_progress" ]; do
+              sleep "$POLL_INTERVAL"
+              RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
+              STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
+              CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+            done
 
             if [ "${STATUS}" == "completed" ]; then
               if [ "${CONCLUSION}" == "success" ]; then
@@ -160,8 +188,10 @@ jobs:
                 echo "Workflow failed for ${REPO}."
                 exit 1
               fi
-            else
-              echo "Workflow not completed yet for ${REPO}. Waiting for $POLL_INTERVAL seconds..."
-              sleep "$POLL_INTERVAL"
             fi
-          done
+          else
+            echo "No in-progress workflow found for ${REPO}. Waiting for $POLL_INTERVAL seconds..."
+          fi
+
+          sleep "$POLL_INTERVAL"
+        done
