file updated

diff --git a/.github/workflows/release-go-libs.yaml b/.github/workflows/release-go-libs.yaml
--- a/.github/workflows/release-go-libs.yaml
+++ b/.github/workflows/release-go-libs.yaml
@@ -18,17 +18,18 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        repo: [
+        repo:
+          [
             "khareRajshree/goiscsi",
             "khareRajshree/gonvme",
-            # "khareRajshree/gocsi",
-            # "khareRajshree/gofsutil",
-            # "khareRajshree/gopowerstore",
-            # "khareRajshree/gopowerscale",
-            # "khareRajshree/gopowermax",
-            # "khareRajshree/gounity",
-            # "khareRajshree/goscaleio",
-            # "khareRajshree/goobjectscale",
+            "khareRajshree/gocsi",
+            "khareRajshree/gofsutil",
+            "khareRajshree/gopowerstore",
+            "khareRajshree/gopowerscale",
+            "khareRajshree/gopowermax",
+            "khareRajshree/gounity",
+            "khareRajshree/goscaleio",
+            "khareRajshree/goobjectscale",
           ]
     steps:
       - name: Trigger Release of ${{ matrix.repo }}
@@ -44,73 +45,10 @@ jobs:
               "sha": "${{ github.sha }}"
             }
 
-  # wait_for_completion:
-  #   name: Wait for Independent Repo Release Completion
-  #   runs-on: ubuntu-latest
-  #   needs: release_independent_repos
-  #   steps:
-  #     - name: Check status of triggered workflows
-  #       run: |
-  #         # GitHub access token
-  #         GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
-  #         POLL_INTERVAL=60  # Check every 60 seconds
-
-  #         # List of repositories to check
-  #         declare -a repos=("khareRajshree/goiscsi" "khareRajshree/gonvme")
-
-  #         for repo in "${repos[@]}"; do
-  #           echo "Checking workflow status for $repo..."
-
-  #           while true; do
-  #             # Get the latest workflow run status for the specific workflow name and event type
-  #             response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${repo}/actions/runs?event=repository_dispatch")
-
-  #             # echo "Response for ${repo}: ${response}"
-
-  #             # Check for authentication errors
-  #             if [[ "${response}" == *"Bad credentials"* ]]; then
-  #               echo "Error: Bad credentials. Please check the provided GitHub token."
-  #               exit 1
-  #             fi
-
-  #             # # Extract the workflow run for the specific 'release-go-libs' workflow
-  #             # workflow_run=$(echo "${response}" | jq -r '.workflow_runs[] | select(.name == "release-go-libs")')
-  #             # if [ -z "$workflow_run" ]; then
-  #             #   echo "No matching workflow run found for 'release-go-libs' in $repo. Retrying..."
-  #             #   sleep "$POLL_INTERVAL"
-  #             #   continue
-  #             # fi
-  #             # # Parse the JSON response to get the workflow run id and status
-  #             # workflow_runs=$(echo "${response}" | jq -c '.workflow_runs[] | select(.name == "release-go-libs")')
-  #             # if [ -z "${workflow_runs}" ]; then
-  #             #   echo "No matching workflow run found for 'release-go-libs' in $repo. Retrying..."
-  #             #   sleep "$POLL_INTERVAL"
-  #             #   continue
-  #             # fi
-
-  #             # echo "Found matching workflow runs for $repo"
-
-  # status=$(echo "${workflow_runs}" | jq -r '[.status] | first')
-  # conclusion=$(echo "${workflow_runs}" | jq -r '[.conclusion] | first')
-
-  # echo "Current status for $repo: $status, conclusion: $conclusion"
-
-  # if [ "${status}" == "completed" ]; then
-  #   if [ "${conclusion}" == "success" ]; then
-  #     echo "Workflow completed successfully for $repo."
-  #     break
-  #   else
-  #     echo "Workflow failed for $repo."
-  #     exit 1
-  #   fi
-  # else
-  #   echo "Workflow not completed yet for $repo. Waiting for $POLL_INTERVAL seconds..."
-  #   sleep "$POLL_INTERVAL"
-  # fi
-  #           done
-  #         done
-
   wait_for_completion:
+    strategy:
+      matrix:
+        repo: ["khareRajshree/goiscsi", "khareRajshree/gonvme"]
     name: Wait for Independent Repo Release Completion
     runs-on: ubuntu-latest
     needs: release_independent_repos
@@ -120,53 +58,46 @@ jobs:
           # GitHub access token
           GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
           POLL_INTERVAL=60  # Check every 60 seconds
+          RETRY_COUNT=0
+          MAX_RETRIES=5
 
-          # List of repositories to check
-          declare -a repos=("khareRajshree/goiscsi" "khareRajshree/gonvme")
-          WORKFLOW_NAME="release-go-libs"
-          WORKFLOW_FILE="release.yaml" # The workflow file name
+          REPO="${{ matrix.repo }}"
+          echo "Checking workflow status for ${REPO}..."
 
-          for repo in "${repos[@]}"; do
-            echo "Checking workflow status for $repo..."
+          while true; do
+            # Get the latest workflow run status for the specified event type
+            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${REPO}/actions/runs?event=repository_dispatch")
 
-            retry_count=0
-            max_retries=5
-
-            while true; do
-              # Get the latest workflow run status for the specified event type
-              response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-                "https://api.github.com/repos/${repo}/actions/runs?event=repository_dispatch")
-
-              # Check if the API call was successful
-              if [ $? -ne 0 ]; then
-                retry_count=$((retry_count + 1))
-                if [ $retry_count -ge $max_retries ]; then
-                  echo "API call failed after $max_retries attempts."
-                  exit 1
-                else
-                  echo "API call failed. Retrying ($retry_count/$max_retries)..."
-                  sleep 5
-                  continue
-                fi
-              fi
-
-              # Parse the JSON response to get the workflow run status
-              status=$(echo "${response}" | jq -r '.workflow_runs[0].status')
-              conclusion=$(echo "${response}" | jq -r '.workflow_runs[0].conclusion')
-
-              if [ "${status}" == "completed" ]; then
-                if [ "${conclusion}" == "success" ]; then
-                  echo "Workflow completed successfully for $repo."
-                  break
-                else
-                  echo "Workflow failed for $repo."
-                  exit 1
-                fi
+            # Check if the API call was successful
+            if [ $? -ne 0 ]; then
+              RETRY_COUNT=$((RETRY_COUNT + 1))
+              if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+                echo "API call failed after $MAX_RETRIES attempts."
+                exit 1
               else
-                echo "Workflow not completed yet for $repo. Waiting for $POLL_INTERVAL seconds..."
-                sleep "$POLL_INTERVAL"
+                echo "API call failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
+                sleep 5
+                continue
               fi
-            done
+            fi
+
+            # Parse the JSON response to get the workflow run status
+            STATUS=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].status')
+            CONCLUSION=$(echo "${RESPONSE}" | jq -r '.workflow_runs[0].conclusion')
+
+            if [ "${STATUS}" == "completed" ]; then
+              if [ "${CONCLUSION}" == "success" ]; then
+                echo "Workflow completed successfully for ${REPO}."
+                break
+              else
+                echo "Workflow failed for ${REPO}."
+                exit 1
+              fi
+            else
+              echo "Workflow not completed yet for ${REPO}. Waiting for $POLL_INTERVAL seconds..."
+              sleep "$POLL_INTERVAL"
+            fi
           done
 
   release_dependent_repo:
